import 'package:flutter/widgets.dart';

import '../../core/extensions/context_extensions.dart';

/// The words for a stored ISO 4217 currency code.
///
/// **Long and mechanical on purpose**, exactly like `CountryLabel`:
/// `context.l10n` has no dynamic key lookup, so the alternative to one arm per
/// currency is a map of English strings — which is hard rule 7 broken with
/// extra steps. `CurrencyConstant` holds the codes, this holds what a seller
/// reads.
///
/// **Its own file, away from `WorkspaceOptionLabel`.** There are as many of
/// these as there are countries now, and left in place they buried the two
/// business-type arms that file exists for.
///
/// **An unknown code falls back to itself.** A workspace created on a later
/// build must still render its row rather than showing a blank.
final class CurrencyLabel {
  static String of(BuildContext context, String code) => switch (code) {
    'AFN' => context.l10n.currencyAfn,
    'ALL' => context.l10n.currencyAll,
    'DZD' => context.l10n.currencyDzd,
    'AOA' => context.l10n.currencyAoa,
    'ARS' => context.l10n.currencyArs,
    'AMD' => context.l10n.currencyAmd,
    'AWG' => context.l10n.currencyAwg,
    'AUD' => context.l10n.currencyAud,
    'AZN' => context.l10n.currencyAzn,
    'BSD' => context.l10n.currencyBsd,
    'BHD' => context.l10n.currencyBhd,
    'BDT' => context.l10n.currencyBdt,
    'BBD' => context.l10n.currencyBbd,
    'BYN' => context.l10n.currencyByn,
    'BZD' => context.l10n.currencyBzd,
    'BMD' => context.l10n.currencyBmd,
    'BTN' => context.l10n.currencyBtn,
    'BOB' => context.l10n.currencyBob,
    'BAM' => context.l10n.currencyBam,
    'BWP' => context.l10n.currencyBwp,
    'BRL' => context.l10n.currencyBrl,
    'GBP' => context.l10n.currencyGbp,
    'BND' => context.l10n.currencyBnd,
    'BGN' => context.l10n.currencyBgn,
    'BIF' => context.l10n.currencyBif,
    'XPF' => context.l10n.currencyXpf,
    'KHR' => context.l10n.currencyKhr,
    'CAD' => context.l10n.currencyCad,
    'CVE' => context.l10n.currencyCve,
    'XCG' => context.l10n.currencyXcg,
    'KYD' => context.l10n.currencyKyd,
    'XAF' => context.l10n.currencyXaf,
    'CLP' => context.l10n.currencyClp,
    'CNY' => context.l10n.currencyCny,
    'COP' => context.l10n.currencyCop,
    'KMF' => context.l10n.currencyKmf,
    'CDF' => context.l10n.currencyCdf,
    'CRC' => context.l10n.currencyCrc,
    'CUP' => context.l10n.currencyCup,
    'CZK' => context.l10n.currencyCzk,
    'DKK' => context.l10n.currencyDkk,
    'DJF' => context.l10n.currencyDjf,
    'DOP' => context.l10n.currencyDop,
    'XCD' => context.l10n.currencyXcd,
    'EGP' => context.l10n.currencyEgp,
    'ERN' => context.l10n.currencyErn,
    'ETB' => context.l10n.currencyEtb,
    'EUR' => context.l10n.currencyEur,
    'FKP' => context.l10n.currencyFkp,
    'FJD' => context.l10n.currencyFjd,
    'GMD' => context.l10n.currencyGmd,
    'GEL' => context.l10n.currencyGel,
    'GHS' => context.l10n.currencyGhs,
    'GIP' => context.l10n.currencyGip,
    'GTQ' => context.l10n.currencyGtq,
    'GNF' => context.l10n.currencyGnf,
    'GYD' => context.l10n.currencyGyd,
    'HTG' => context.l10n.currencyHtg,
    'HNL' => context.l10n.currencyHnl,
    'HKD' => context.l10n.currencyHkd,
    'HUF' => context.l10n.currencyHuf,
    'ISK' => context.l10n.currencyIsk,
    'INR' => context.l10n.currencyInr,
    'IDR' => context.l10n.currencyIdr,
    'IRR' => context.l10n.currencyIrr,
    'IQD' => context.l10n.currencyIqd,
    'ILS' => context.l10n.currencyIls,
    'JMD' => context.l10n.currencyJmd,
    'JPY' => context.l10n.currencyJpy,
    'JOD' => context.l10n.currencyJod,
    'KZT' => context.l10n.currencyKzt,
    'KES' => context.l10n.currencyKes,
    'KWD' => context.l10n.currencyKwd,
    'KGS' => context.l10n.currencyKgs,
    'LAK' => context.l10n.currencyLak,
    'LBP' => context.l10n.currencyLbp,
    'LSL' => context.l10n.currencyLsl,
    'LRD' => context.l10n.currencyLrd,
    'LYD' => context.l10n.currencyLyd,
    'MOP' => context.l10n.currencyMop,
    'MKD' => context.l10n.currencyMkd,
    'MGA' => context.l10n.currencyMga,
    'MWK' => context.l10n.currencyMwk,
    'MYR' => context.l10n.currencyMyr,
    'MVR' => context.l10n.currencyMvr,
    'MRU' => context.l10n.currencyMru,
    'MUR' => context.l10n.currencyMur,
    'MXN' => context.l10n.currencyMxn,
    'MDL' => context.l10n.currencyMdl,
    'MNT' => context.l10n.currencyMnt,
    'MAD' => context.l10n.currencyMad,
    'MZN' => context.l10n.currencyMzn,
    'MMK' => context.l10n.currencyMmk,
    'NAD' => context.l10n.currencyNad,
    'NPR' => context.l10n.currencyNpr,
    'ANG' => context.l10n.currencyAng,
    'TWD' => context.l10n.currencyTwd,
    'NZD' => context.l10n.currencyNzd,
    'NIO' => context.l10n.currencyNio,
    'NGN' => context.l10n.currencyNgn,
    'KPW' => context.l10n.currencyKpw,
    'NOK' => context.l10n.currencyNok,
    'OMR' => context.l10n.currencyOmr,
    'PKR' => context.l10n.currencyPkr,
    'PAB' => context.l10n.currencyPab,
    'PGK' => context.l10n.currencyPgk,
    'PYG' => context.l10n.currencyPyg,
    'PEN' => context.l10n.currencyPen,
    'PHP' => context.l10n.currencyPhp,
    'PLN' => context.l10n.currencyPln,
    'QAR' => context.l10n.currencyQar,
    'RON' => context.l10n.currencyRon,
    'RUB' => context.l10n.currencyRub,
    'RWF' => context.l10n.currencyRwf,
    'SHP' => context.l10n.currencyShp,
    'SVC' => context.l10n.currencySvc,
    'WST' => context.l10n.currencyWst,
    'SAR' => context.l10n.currencySar,
    'RSD' => context.l10n.currencyRsd,
    'SCR' => context.l10n.currencyScr,
    'SLE' => context.l10n.currencySle,
    'SGD' => context.l10n.currencySgd,
    'SBD' => context.l10n.currencySbd,
    'SOS' => context.l10n.currencySos,
    'ZAR' => context.l10n.currencyZar,
    'KRW' => context.l10n.currencyKrw,
    'SSP' => context.l10n.currencySsp,
    'LKR' => context.l10n.currencyLkr,
    'SDG' => context.l10n.currencySdg,
    'SRD' => context.l10n.currencySrd,
    'SZL' => context.l10n.currencySzl,
    'SEK' => context.l10n.currencySek,
    'CHF' => context.l10n.currencyChf,
    'SYP' => context.l10n.currencySyp,
    'STN' => context.l10n.currencyStn,
    'TJS' => context.l10n.currencyTjs,
    'TZS' => context.l10n.currencyTzs,
    'THB' => context.l10n.currencyThb,
    'TOP' => context.l10n.currencyTop,
    'TTD' => context.l10n.currencyTtd,
    'TND' => context.l10n.currencyTnd,
    'TRY' => context.l10n.currencyTry,
    'TMT' => context.l10n.currencyTmt,
    'USD' => context.l10n.currencyUsd,
    'UGX' => context.l10n.currencyUgx,
    'UAH' => context.l10n.currencyUah,
    'AED' => context.l10n.currencyAed,
    'UYU' => context.l10n.currencyUyu,
    'UZS' => context.l10n.currencyUzs,
    'VUV' => context.l10n.currencyVuv,
    'VES' => context.l10n.currencyVes,
    'VED' => context.l10n.currencyVed,
    'VND' => context.l10n.currencyVnd,
    'XOF' => context.l10n.currencyXof,
    'YER' => context.l10n.currencyYer,
    'ZMW' => context.l10n.currencyZmw,
    'ZWG' => context.l10n.currencyZwg,
    _ => code,
  };
}
