import 'package:flutter/material.dart';
import 'package:material_symbols_icons/symbols.dart';

/// The app's semantic glyph registry.
///
/// Call sites ask for what an icon means. This file alone decides whether the
/// glyph comes from Flutter's Material Icons or the Material Symbols font.
final class AppIconConstant {
  static const IconData accountBalance = Symbols.account_balance_rounded;
  static const IconData accountBalanceWallet =
      Symbols.account_balance_wallet_rounded;
  static const IconData accountTree = Symbols.account_tree_rounded;
  static const IconData delete = Icons.delete_outline_rounded;
  static const IconData moreVert = Icons.more_vert_rounded;
  static const IconData addBox = Symbols.add_box_rounded;
  static const IconData add = Symbols.add_rounded;
  static const IconData archive = Symbols.archive_rounded;
  static const IconData arrowForward = Symbols.arrow_forward_rounded;
  static const IconData assignmentReturn = Symbols.assignment_return_rounded;
  static const IconData autorenew = Symbols.autorenew_rounded;
  static const IconData badge = Symbols.badge_rounded;
  static const IconData barChart = Symbols.bar_chart_rounded;
  static const IconData barcodeScanner = Symbols.barcode_scanner_rounded;
  static const IconData bolt = Symbols.bolt_rounded;
  static const IconData calculate = Symbols.calculate_rounded;
  static const IconData calendarMonth = Symbols.calendar_month_rounded;
  static const IconData cameraswitch = Symbols.cameraswitch_rounded;
  static const IconData category = Symbols.category_rounded;
  static const IconData checkCircle = Symbols.check_circle_rounded;
  static const IconData check = Symbols.check_rounded;
  static const IconData chevronRight = Symbols.chevron_right_rounded;
  static const IconData close = Symbols.close_rounded;
  static const IconData contentCopy = Symbols.content_copy_rounded;
  static const IconData contrast = Symbols.contrast_rounded;
  static const IconData creditCard = Symbols.credit_card_rounded;
  static const IconData currencyExchange = Symbols.currency_exchange_rounded;
  static const IconData database = Symbols.database_rounded;
  static const IconData deleteForever = Symbols.delete_forever_rounded;
  static const IconData description = Symbols.description_rounded;
  static const IconData directionsCar = Symbols.directions_car_rounded;
  static const IconData download = Symbols.download_rounded;
  static const IconData edit = Symbols.edit_rounded;
  static const IconData error = Symbols.error_rounded;
  static const IconData expandMore = Symbols.expand_more_rounded;
  static const IconData filterAltOff = Symbols.filter_alt_off_rounded;
  static const IconData flashlightOn = Symbols.flashlight_on_rounded;
  static const IconData function = Symbols.function_rounded;
  static const IconData gavel = Symbols.gavel_rounded;
  static const IconData grade = Symbols.grade_rounded;
  static const IconData groupAdd = Symbols.group_add_rounded;
  static const IconData group = Symbols.group_rounded;
  static const IconData history = Symbols.history_rounded;
  static const IconData home = Symbols.home_rounded;
  static const IconData hourglassBottom = Symbols.hourglass_bottom_rounded;
  static const IconData hourglassTop = Symbols.hourglass_top_rounded;
  static const IconData hub = Symbols.hub_rounded;
  static const IconData image = Symbols.image_rounded;
  static const IconData inbox = Symbols.inbox_rounded;
  static const IconData info = Symbols.info_rounded;
  static const IconData inventory = Symbols.inventory_2_rounded;
  static const IconData keyboardArrowDown = Symbols.keyboard_arrow_down_rounded;
  static const IconData language = Symbols.language_rounded;
  static const IconData localMall = Symbols.local_mall_rounded;
  static const IconData localOffer = Symbols.local_offer_rounded;
  static const IconData localShipping = Symbols.local_shipping_rounded;
  static const IconData lock = Symbols.lock_rounded;
  static const IconData login = Symbols.login_rounded;
  static const IconData logout = Symbols.logout_rounded;
  static const IconData markEmailRead = Symbols.mark_email_read_rounded;
  static const IconData menu = Symbols.menu_rounded;
  static const IconData notifications = Symbols.notifications_rounded;
  static const IconData openInNew = Symbols.open_in_new_rounded;
  static const IconData package = Symbols.package_2_rounded;
  static const IconData payments = Symbols.payments_rounded;
  static const IconData personRemove = Symbols.person_remove_rounded;
  static const IconData person = Symbols.person_rounded;
  static const IconData photoCamera = Symbols.photo_camera_rounded;
  static const IconData photoLibrary = Symbols.photo_library_rounded;
  static const IconData pointOfSale = Symbols.point_of_sale_rounded;
  static const IconData priceChange = Symbols.price_change_rounded;
  static const IconData priorityHigh = Symbols.priority_high_rounded;
  static const IconData public = Symbols.public_rounded;
  static const IconData qrCodeScanner = Symbols.qr_code_scanner_rounded;
  static const IconData radioButtonUnchecked =
      Symbols.radio_button_unchecked_rounded;
  static const IconData receiptLong = Symbols.receipt_long_rounded;
  static const IconData receipt = Symbols.receipt_rounded;
  static const IconData reply = Symbols.reply_rounded;
  static const IconData restartAlt = Symbols.restart_alt_rounded;
  static const IconData restore = Symbols.restore_rounded;
  static const IconData rocketLaunch = Symbols.rocket_launch_rounded;
  static const IconData savings = Symbols.savings_rounded;
  static const IconData schedule = Symbols.schedule_rounded;
  static const IconData science = Symbols.science_rounded;
  static const IconData searchOff = Symbols.search_off_rounded;
  static const IconData search = Symbols.search_rounded;
  static const IconData sell = Symbols.sell_rounded;
  static const IconData settings = Symbols.settings_rounded;
  static const IconData shelves = Symbols.shelves;
  static const IconData shield = Symbols.shield_rounded;
  static const IconData shoppingBag = Symbols.shopping_bag_rounded;
  static const IconData storefront = Symbols.storefront_rounded;
  static const IconData summarize = Symbols.summarize_rounded;
  static const IconData thumbDown = Symbols.thumb_down_rounded;
  static const IconData thumbUp = Symbols.thumb_up_rounded;
  static const IconData travelExplore = Symbols.travel_explore_rounded;
  static const IconData trendingUp = Symbols.trending_up_rounded;
  static const IconData tune = Symbols.tune_rounded;
  static const IconData unarchive = Symbols.unarchive_rounded;
  static const IconData warehouse = Symbols.warehouse_rounded;
  static const IconData warning = Symbols.warning_rounded;
  static const IconData workspacePremium = Symbols.workspace_premium_rounded;
}
